sudo: required
language: c
script:
- bash build-and-test.sh
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env: PACKAGES_INSTALL="libusb-1.0-0-dev libncurses5-dev gcc-multilib"
deploy:
  provider: releases
  skip_cleanup: true
  api_key
    secure: b0a1cd06e47c981e898fd27824c2b24915f7f148
  file_glob: true
  file: $(pwd)/build/*.zip
  on:
    tags: true
    all_branches: true
